client/urls.py
from django.urls import path
from client import views


app_name = "client"

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.dashboard_login, name="login"),
    path('logout/', views.dashboard_logout, name="logout"),
    
    path('category_list/', views.category_list, name="category_list"),
    path('category_create/', views.category_create, name="category_create"),
    path('<int:pk>/category_edit/', views.category_edit, name="category_edit"),
    path('<int:pk>/category_delete/', views.category_delete, name="category_delete"),
    
    
    path('new_list/', views.new_list, name="new_list"),
    path('new_create/', views.new_create, name="new_create"),
    path('<int:pk>/new_edit/', views.new_edit, name="new_edit"),
    path('<int:pk>/new_delete/', views.new_delete, name="new_delete"),
    
    
    path('course_list/', views.course_list, name="course_list"),
    path('course_create/', views.course_create, name="course_create"),
    path('<int:pk>/course_edit/', views.course_edit, name="course_edit"),
    path('<int:pk>/course_delete/', views.course_delete, name="course_delete"),
    
    
    path('miracles_list/', views.miracles_list, name="miracles_list"),
    path('<int:pk>/miracles_edit/', views.miracles_edit, name="miracles_edit"),
    



    path('openclass_list/', views.openclass_list, name="openclass_list"),
    path('openclass_create/', views.openclass_create, name="openclass_create"),
    path('<int:pk>/openclass_edit/', views.openclass_edit, name="openclass_edit"),
    path('<int:pk>/openclass_delete/', views.openclass_delete, name="openclass_delete"),
    
    
    path('project_list/', views.project_list, name="project_list"),
    path('video_create/', views.video_create, name="video_create"),
    path('<int:pk>/video_edit/', views.video_edit, name="video_edit"),
    path('<int:pk>/video_delete/', views.video_delete, name="video_delete"),
    
    path('video_list/', views.video_list, name="video_list"),
    path('project_create/', views.project_create, name="project_create"),
    path('<int:pk>/project_edit/', views.project_edit, name="project_edit"),
    path('<int:pk>/project_delete/', views.project_delete, name="project_delete"),
    
    path('questions_list/', views.questions_list, name="questions_list"),
    path('questions_create/', views.questions_create, name="questions_create"),
    path('<int:pk>/questions_edit/', views.questions_edit, name="questions_edit"),
    path('<int:pk>/questions_delete/', views.questions_delete, name="questions_delete"),

    path('modul_list/', views.modul_list, name="modul_list"),
    path('modul_create/', views.modul_create, name="modul_create"),
    path('<int:pk>/modul_edit/', views.modul_edit, name="modul_edit"),
    path('<int:pk>/modul_delete/', views.modul_delete, name="modul_delete"),


]

main/urls.py
from django.urls import path, include
from main.views import *



app_name = "main"

urlpatterns = [
    path("", index, name="index"),
    path("login_course/", login_course, name="login_course"),
    path("course/", course, name="course"),
    path("new_details/<int:id>/", new_details, name="new_details"),
    path("news/", news, name="news"),
    path("course_details/<int:id>/", course_details, name="course_details"),
    path("project/<int:id>/", project, name="project"),
    path("teacher_course/<int:id>/", teacher_course, name="teacher_course"),
    path("login_course_now/<int:id>/", login_course_now, name="login_course_now"),
]

setting/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('xumoyunx/', admin.site.urls),
    path("", include("main.urls")),
    path("client/", include("client.urls")),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/dashboard/course/form.html
{% extends 'dashboard/base.html' %}
{% load static %}


	
	

{% block content %}

<main class="ttr-wrapper">
    <div class="container-fluid">
        <div class="db-breadcrumb">
            <h4 class="breadcrumb-title">Yangiliklar qo'shish</h4>
            <ul class="db-breadcrumb-list">
                <li><a href="#"><i class="fa fa-home"></i>Asosiy</a></li>
                <li>Yangiliklar qo'shish</li>
            </ul>
        </div>	
        <div class="row">
            <!-- Your Profile Views Chart -->
            <div class="col-lg-12 m-b30">
                <div class="widget-box">
                    <div class="wc-title">
                        <h4>Yangiliklar qo'shish</h4>
                    </div>
                    <div class="widget-inner">
                        <form method="post"  enctype="multipart/form-data" class="edit-profile m-b30">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12">
                                    <div class="ml-auto">
                                        <h3><b>1. Ustoz</b></h3>
                                    </div>
                                </div>
                                <div class="form-group col-6">
                                    <label class="col-form-label">To'liq qilib yozing   </label>
                                    <div>
                                        {{ form.mentor }}
                                        {% comment %} <input class="form-control" type="text" value=""> {% endcomment %}
                                    </div>
                                </div> 
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <div class="ml-auto">
                                        <h3><b>2. Kurs nomi</b></h3>
                                    </div>
                                </div>
                                <div class="form-group col-6">
                                    <label class="col-form-label">To'liq qilib yozing   </label>
                                    <div>
                                        {{ form.course_name }}
                                        {% comment %} <input class="form-control" type="text" value=""> {% endcomment %}
                                    </div>
                            
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <div class="ml-auto">
                                        <h3><b>3. Kurs haqida malumot</b></h3>
                                    </div>
                                </div>
                                <div class="form-group col-6">
                                    <label class="col-form-label">To'liq qilib yozing   </label>
                                    <div>
                                        {{ form.text }}
                                        {% comment %} <input class="form-control" type="text" value=""> {% endcomment %}
                                    </div>
                            
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-12">
                                    <div class="ml-auto">
                                        <h3><b>4. Kurs Modul</b></h3>
                                    </div>
                                </div>
                                <div class="form-group col-6">
                                    <label class="col-form-label">To'liq qilib yozing   </label>
                                    <div>
                                        {{ form.course_table }}
                                        {% comment %} <input class="form-control" type="text" value=""> {% endcomment %}
                                    </div>
                            
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-12">
                                    <div class="ml-auto">
                                        <h3><b>5. Dars soni</b></h3>
                                    </div>
                                </div>
                                <div class="form-group col-6">
                                    <label class="col-form-label">To'liq qilib yozing   </label>
                                    <div>
                                        {{ form.lesson_number }}
                                        {% comment %} <input class="form-control" type="text" value=""> {% endcomment %}
                                    </div>
                            
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-12">
                                    <div class="ml-auto">
                                        <h3><b>6. Kurs oyni</b></h3>
                                    </div>
                                </div>
                                <div class="form-group col-6">
                                    <label class="col-form-label">To'liq qilib yozing   </label>
                                    <div>
                                        {{ form.month }}
                                        {% comment %} <input class="form-control" type="text" value=""> {% endcomment %}
                                    </div>
                            
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-12">
                                    <div class="ml-auto">
                                        <h3><b>7. Kurs bonus</b></h3>
                                    </div>
                                </div>
                                <div class="form-group col-6">
                                    <label class="col-form-label">To'liq qilib yozing   </label>
                                    <div>
                                        {{ form.bonus }}
                                        {% comment %} <input class="form-control" type="text" value=""> {% endcomment %}
                                    </div>
                            
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-12">
                                    <div class="ml-auto">
                                        <h3><b>3. Rasm joylash</b></h3>
                                    </div>
                                </div>
                                <div class="form-group col-6">
                                    <label class="col-form-label">Filen joylang   </label>
                                    <div>
                                        {{ form.img }}
                                        {% comment %} <input class="form-control" type="text" value=""> {% endcomment %}
                                    </div>
                            
                                </div>
                            </div>
                                
                               
                               
                               
                                
                                
                                
                                <div class="col-12">
                                    <button type="submit" class="btn"><i class="fa fa-fw fa-plus-circle"></i>Saqlash</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- Your Profile Views Chart END-->
        </div>
    </div>
</main>

{% endblock %}

templates/dashboard/course/list.html
{% extends 'dashboard/base.html' %}
{% load static %}


	
	

{% block content %}






	<!--Main container start -->
	<main class="ttr-wrapper">
		<div class="container-fluid">
			<div class="db-breadcrumb">
				<h4 class="breadcrumb-title">Kurslar</h4>
				<ul class="db-breadcrumb-list">
					<li><a href="#"><i class="fa fa-home"></i>Asosiy</a></li>
					<li>Kurslar</li>
				</ul>
			</div>	
			<div class="row">
				<!-- Your Profile Views Chart -->
				<div class="col-lg-12 m-b30">
					<div class="widget-box">
						<div class="wc-title">
							<h4>Bizni Kurslari</h4>
						</div>
						<div class="widget-inner">
							<div class="card-courses-list admin-courses">
								
								<div class="card-courses-full-dec">
									<div class="card-courses-title">
										{% comment %} <h4>{{ i.last_name }}</h4> {% endcomment %}
									</div>
									
									<div class="row card-courses-dec">
										<div class="col-md-12">
											{% comment %} <h6 class="m-b10">{{ i.direction }}</h6> {% endcomment %}
											{% comment %} <p>Lorem ipsum dolor sit amet, est ei idque voluptua copiosae, pro detracto disputando reformidans at, ex vel suas eripuit. Vel alii zril maiorum ex, mea id sale eirmod epicurei. Sit te possit senserit, eam alia veritus maluisset ei, id cibo vocent ocurreret per. Te qui doming doctus referrentur, usu debet tamquam et. Sea ut nullam aperiam, mei cu tollit salutatus delicatissimi. </p>	 {% endcomment %}
										</div>
										<div class="col-md-12">
											<a href="{% url 'client:course_create' %}" class="btn green radius-xl outline">Qoʻshish</a>
										</div>
									</div>
									
								</div>
							</div>
							{% for i in course %}
							<div class="card-courses-list admin-courses">
								<div class="card-courses-media">
									<img src="{{ i.img.url }}" alt=""/>
								</div>
								<div class="card-courses-full-dec">
									<div class="card-courses-title">
										<h4>{{ i.course_name }}</h4>
									</div>
									<div class="card-courses-list-bx">
										<ul class="card-courses-view">
											<li class="card-courses-user">
												<div class="card-courses-user-pic">
													<img src="{{ i.mentor.img.url }}" alt=""/>
												</div>
												<div class="card-courses-user-info">
													<h5>Ustoz</h5>
													<h4>{{ i.mentor.last_name }}</h4>
												</div>
											</li>
											<li class="card-courses-categories">
												<h5>Yo'nalsih</h5>
												<h4>{{ i.mentor.direction }}</h4>
											</li>
											<li class="card-courses-categories">
												<h5>Modul</h5>
												<h4>{{ i.course_table }}</h4>
											</li>
											<li class="card-courses-categories">
												<h5>OY</h5>
												<h4>{{ i.month }}</h4>
											</li>
											<li class="card-courses-categories">
												<h5>Dasr Soni</h5>
												<h4>{{ i.lesson_number }}</h4>
											</li>

											
											
										</ul>
									</div>
									<div class="row card-courses-dec">
										<div class="col-md-12">
											<h6 class="m-b10"><b>Bonus:</b> {{ i.bonus }}</h6>
											<p>{{ i.text }}</p>	
										</div>
										<div class="col-md-12">
											<a href="{% url 'client:course_edit' i.id %}" class="btn green radius-xl outline">Taxrirlash</a>
											<a href="{% url 'client:course_delete' i.id %}" class="btn red outline radius-xl ">O'chirish</a>
										</div>
									</div>
									
								</div>
							</div>
							{% endfor %}

							
							
						</div>
					</div>
				</div>
				<!-- Your Profile Views Chart END-->
			</div>
		</div>
	</main>
	<div class="ttr-overlay"></div>


{% endblock %}